server {
    listen 80;
    server_name _;

    # Traefik envia o path completo /orcamento/...
    location /orcamento/ {
        alias /usr/share/nginx/html/orcamento/;
        index index.html;
        try_files $uri $uri/ =404;
    }

    location = /orcamento {
        return 301 /orcamento/;
    }
}
